<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (recall)

| **Term**   |  **Brief Description**                                                                                                                                                                                                                          |
|------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Subsetting | Accessing a smaller selection of elements derived from a larger collection (lists/arrays). Whatever is in the smaller collection is also present in the larger collection.                                                                      |
| Indexing   | Selecting an element from a list/array/sequence using its position (i.e. index) in the sequence.  (indexing starts from 0 in python.)                                                                                                           |
| Slicing    | Selecting a RANGE of elements.  Must specify to python where to start and where to end, i.e.'define' the range. (same for both array and list) _If slice with [a:z], the slice will start at a and end at z-1, giving a total of z-1 elements._ |
| Masking    | Upon setting a specific condition on what you want your mask to do/be in the array, masking will allow python to return and show only elements within the array that satisfies the conditions (true!).                                          |

## Exercise 2 (find 'odd' letters)


In [2]:
# Use masking to subset the letters that correspond to the odd numbers. I.e., get the result [A, C, E, G, I].
# ps i followed the steps provided in the exercise instructions
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

print(np_array_2d[:10,0])                                     # Subset all the first elements 
int_array_2d = np_array_2d[:10,0].astype(int)               # Convert them into integers 
print(int_array_2d%2)                                   # Get the remainders of the integers after division by 2
my_mask = int_array_2d%2 == 0  
print(~my_mask)                            # Use above results to create a mask that checks if remainder is zero or not. 
                                            # This identifies location of the odd numbers
print(np_array_2d[~my_mask, 1])             # Use the mask and extract corresponding second elements, i.e. the letters. 
                                            # From np_array_2d, give all rows where ~my_mask is True, but only column 1.

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]
['A' 'C' 'E' 'G' 'I']


## Exercise 3 

In [5]:
py_list = [[66, 50, 57, -1, -1],
            [92, -1, 88, -1, -1],
            [75, -1, -1, 76, -1],
            [-1, 51, 87, -1, -1],
            [71, -1, 67, -1, 69]]
np_array = np.array(py_list)
# using masking, change:
    # values below 50 to -1,
    # values above 50 to +1, and
    # values equal to 50 to 0.

mask_below = np_array < 50
mask_above = np_array > 50
mask_equal = np_array == 50

# replacement values 
np_array[mask_below] = -1
np_array[mask_above] = 1
np_array[mask_equal] = 0
print(np_array)









[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
