<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

# **Exercise 1 (Recallation on Lists and Arrays)**

### 1. similarities
1. both lists and arrays are ways in python to store data which can be accessed later. 
1. order of items matter in both lists and arrays 

### 2. differences 
1. subsetting by masking only works for arrays, not lists 
1. Lists don't support element-wise arithmetic, but arrays do.
    - **example: additional prompt below!**

### 3. what is a dictionary?
A dictionary can be used to store two sets of data that would otherwise usually require two lists to hold. It also uses a 'key' to access the corresponding value/item. 

In [15]:
# Exercise 1 Part 2(Additional Prompt): Lists vs Arrays (Adding & Multiplication)
import numpy as np
list1 = [1, 2, 3, 4, 5]
list2 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
array2 = np.array(list2)

#Adding number - won't work for lists (error)
print(array1 + 10) 
print(array2 + 10)

#Adding another list 
print(list1 + list2)        #causes list to grow 
print(array1 + array2)      #element-wise operation 

#Multiplying by a number 
print(list1*2)              #causes list to grow 
print(array1*2)             #element-wise operation



[11 12 13 14 15]
[20 30 40 50 60]
[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


# **Exercise 2 (Indexing 1)**

In [ ]:
# print out elements with odd numbers
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0]) # Prints 'a1'
print(py_list[2]) # Prints 'c3'
print(py_list[4]) # Prints 'e5'
print(py_list[6]) # Prints 'g7'
print(py_list[8]) # Prints 'i9'

a1
c3
e5
g7
i9


# **Exercise 3 (Indexing 2)**

In [3]:
# access element at index 4 using forward and backward indexing 
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']
# forward indexing
print(elements[5])                  # first element at the start of sequence is index 0
                                    # position = index + 1

# backward indexing
print(elements[-4])                 # last element from the back of the sequence is index -1


Carbon
Nitrogen


# **Exercise 4 (How many ones)**

In [ ]:
import numpy as np
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
np_numbers = np.array(numbers)     
my_mask = np_numbers == 1    
my_mask
sum(my_mask)

np.int64(9)

# **Exercise 5**

In [ ]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
array_x_1 = np.array(x_1)
array_x_2 = np.array(x_2)

# determine means 
print('mean of x_1 =', np.mean(array_x_1))
print('mean of x_2 =', np.mean(array_x_2))

# determine standard deviations
print('stdev of x_1 =', np.std(array_x_1))
print('stdev of x_2 =', np.std(array_x_2))

# numerator 
mean_x1 = 38.5 
mean_x2 = 302.5
x1 = array_x_1-mean_x1
x2 = array_x_2-mean_x2
numerator = sum(x1*x2)
print('numerator =', numerator)

# denominator 
denominator = np.sqrt(sum((x1)**2)*sum((x2)**2))
print('denominator =', denominator)

# find r 
r = numerator/denominator
print(r)

# cross-check value of r with function 
print(np.corrcoef(array_x_1, array_x_2))





mean of x_1 = 38.5
mean of x_2 = 302.5
stdev of x_1 = 32.41990129534635
stdev of x_2 = 326.0893282522444
numerator = 104362.5
denominator = 105717.8383540356
0.9871796626270701
[[1.         0.98717966]
 [0.98717966 1.        ]]
